import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(process.cwd(), '.env') });

const DB_URL = process.env.DATABASE_URL!;

// ── Schemas (inline for seed) ─────────────────────────────────────
const categorySchema = new mongoose.Schema({ name: String, slug: String, icon: String, image: String, parent: { type: mongoose.Schema.Types.ObjectId, default: null }, level: { type: Number, default: 0 }, order: Number, isActive: { type: Boolean, default: true }, isDeleted: { type: Boolean, default: false }, productCount: { type: Number, default: 0 } }, { timestamps: true });
const Category = mongoose.model('Category', categorySchema);

const productSchema = new mongoose.Schema({
    name: String, slug: String, sku: String, description: String, shortDescription: String,
    price: Number, originalPrice: Number, discount: Number,
    thumbnail: String, images: [String],
    category: mongoose.Schema.Types.ObjectId, subcategory: { type: mongoose.Schema.Types.ObjectId, default: null },
    brand: String, stock: Number, unit: { type: String, default: 'piece' },
    status: { type: String, default: 'active' }, isFeatured: Boolean, isDeleted: { type: Boolean, default: false },
    tags: [String], colors: [String], colorHex: [String], material: [String],
    pattern: String, gender: String, aiLabels: [String],
    specifications: [{ key: String, value: String }],
    weight: Number, dimensions: { length: Number, width: Number, height: Number },
    metaTitle: String, metaDescription: String, metaKeywords: [String],
    rating: { type: Number, default: 0 }, reviewCount: { type: Number, default: 0 },
    totalSold: { type: Number, default: 0 }, viewCount: { type: Number, default: 0 },
}, { timestamps: true });
const Product = mongoose.model('Product', productSchema);

async function seed() {
    await mongoose.connect(DB_URL);
    console.log('✅ MongoDB Connected');

    // Clear existing
    await Category.deleteMany({});
    await Product.deleteMany({});
    console.log('🗑️  Cleared old data');

    // ── Categories ─────────────────────────────────────────────────
    const cats = await Category.insertMany([
        { name: 'Fashion', slug: 'fashion', icon: '👗', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', level: 0, order: 1 },
        { name: 'Electronics', slug: 'electronics', icon: '📱', image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400', level: 0, order: 2 },
        { name: 'Shoes', slug: 'shoes', icon: '👟', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', level: 0, order: 3 },
        { name: 'Accessories', slug: 'accessories', icon: '⌚', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400', level: 0, order: 4 },
        { name: 'Home & Living', slug: 'home-living', icon: '🏠', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400', level: 0, order: 5 },
        { name: 'Sports', slug: 'sports', icon: '⚽', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400', level: 0, order: 6 },
    ]);

    const [fashion, electronics, shoes, accessories, home, sports] = cats;

    // ── Products ────────────────────────────────────────────────────
    const products = [
        // ── FASHION (8 products) ──────────────────────────────────────
        {
            name: 'Premium Cotton Formal Shirt (White)', slug: 'premium-cotton-formal-shirt-white', sku: 'FSH-001',
            description: 'A premium quality formal shirt made from 100% Egyptian cotton. Perfect for office wear, formal events, and business meetings. Features a slim-fit design with a classic collar and button-down front. Easy to wash and wrinkle-resistant.',
            shortDescription: 'Premium 100% Egyptian cotton formal shirt with slim-fit design.',
            price: 2500, originalPrice: 3200, discount: 22, thumbnail: 'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=600',
            images: ['https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=600', 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600'],
            category: fashion._id, brand: 'Raymond', stock: 150, isFeatured: true, gender: 'men',
            tags: ['formal shirt', 'cotton shirt', 'men shirt', 'office wear', 'white shirt', 'slim fit'],
            colors: ['white'], colorHex: ['#FFFFFF'], material: ['cotton'],
            pattern: 'solid', aiLabels: ['dress shirt', 'shirt', 'clothing', 'formal'],
            specifications: [{ key: 'Material', value: '100% Egyptian Cotton' }, { key: 'Fit', value: 'Slim Fit' }, { key: 'Collar', value: 'Classic Collar' }, { key: 'Care', value: 'Machine Washable' }],
            weight: 250, metaTitle: 'Premium White Cotton Formal Shirt - Men\'s Slim Fit', metaDescription: 'Buy premium white formal shirt made from Egyptian cotton. Perfect office and business wear.', metaKeywords: ['formal shirt', 'cotton shirt', 'men formal'], rating: 4.5, reviewCount: 48, totalSold: 230,
        },
        {
            name: 'Floral Print Summer Maxi Dress', slug: 'floral-print-summer-maxi-dress', sku: 'FDR-002',
            description: 'A beautiful floral print maxi dress perfect for summer occasions. Made from breathable chiffon fabric that keeps you cool. Features an A-line silhouette, V-neck design, and adjustable straps. Ideal for beach parties, casual outings, and picnics.',
            shortDescription: 'Breathable chiffon floral maxi dress with V-neck design.',
            price: 3800, originalPrice: 5000, discount: 24, thumbnail: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600',
            images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600', 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600'],
            category: fashion._id, brand: 'Zara', stock: 80, isFeatured: true, gender: 'women',
            tags: ['maxi dress', 'floral dress', 'summer dress', 'women dress', 'chiffon', 'beach wear'],
            colors: ['blue', 'pink', 'floral'], colorHex: ['#4A90D9', '#FF6B9D'], material: ['chiffon'],
            pattern: 'floral', aiLabels: ['dress', 'clothing', 'summer wear', 'women fashion'],
            specifications: [{ key: 'Material', value: 'Chiffon' }, { key: 'Style', value: 'Maxi A-Line' }, { key: 'Neckline', value: 'V-Neck' }, { key: 'Length', value: 'Full Length (Maxi)' }],
            weight: 300, metaTitle: 'Floral Summer Maxi Dress for Women', metaDescription: 'Beautiful floral print chiffon maxi dress perfect for summer.', metaKeywords: ['maxi dress', 'floral', 'summer dress'], rating: 4.7, reviewCount: 92, totalSold: 415,
        },
        {
            name: 'Slim Fit Denim Jeans (Dark Blue)', slug: 'slim-fit-denim-jeans-dark-blue', sku: 'JNS-003',
            description: 'Classic slim-fit denim jeans in dark blue wash. Made from premium denim with 2% elastane for stretch comfort. Features five-pocket styling, zip fly with button closure. Versatile enough for casual and semi-formal occasions.',
            shortDescription: 'Classic slim-fit dark blue denim jeans with stretch comfort.',
            price: 3200, originalPrice: 4000, discount: 20, thumbnail: 'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=600',
            images: ['https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=600'],
            category: fashion._id, brand: 'Levi\'s', stock: 200, isFeatured: false, gender: 'men',
            tags: ['jeans', 'denim', 'slim fit', 'pants', 'men jeans', 'dark jeans', 'casual wear'],
            colors: ['dark blue', 'navy'], colorHex: ['#1C2951', '#1F305E'], material: ['denim', 'elastane'],
            pattern: 'solid', aiLabels: ['jeans', 'denim', 'pants', 'clothing'],
            specifications: [{ key: 'Material', value: '98% Cotton 2% Elastane' }, { key: 'Fit', value: 'Slim Fit' }, { key: 'Rise', value: 'Mid Rise' }, { key: 'Closure', value: 'Zip Fly + Button' }],
            weight: 600, rating: 4.4, reviewCount: 67, totalSold: 320,
        },
        {
            name: 'Women Hoodie Sweatshirt (Oversized)', slug: 'women-hoodie-sweatshirt-oversized', sku: 'HOD-004',
            description: 'Cozy oversized hoodie sweatshirt for women. Made from soft fleece-lined cotton blend for maximum warmth. Features a kangaroo pocket, adjustable drawstring hood, and relaxed fit. Perfect for lounging, gym, or casual street style.',
            shortDescription: 'Cozy oversized fleece-lined hoodie for women.',
            price: 2200, originalPrice: 2800, discount: 21, thumbnail: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600',
            images: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600'],
            category: fashion._id, brand: 'H&M', stock: 120, gender: 'women',
            tags: ['hoodie', 'sweatshirt', 'oversized', 'women top', 'casual wear', 'winter wear'],
            colors: ['grey', 'beige'], colorHex: ['#9E9E9E', '#D2C5A0'], material: ['cotton', 'fleece'],
            pattern: 'solid', aiLabels: ['hoodie', 'sweatshirt', 'clothing', 'casual top'],
            specifications: [{ key: 'Material', value: '80% Cotton 20% Polyester Fleece' }, { key: 'Fit', value: 'Oversized' }, { key: 'Hood', value: 'Adjustable Drawstring' }, { key: 'Pocket', value: 'Kangaroo Pocket' }],
            weight: 500, rating: 4.6, reviewCount: 54, totalSold: 180,
        },
        {
            name: 'Silk Blend Saree with Blouse Piece', slug: 'silk-blend-saree-with-blouse-piece', sku: 'SAR-005',
            description: 'Elegant silk blend saree with intricate zari border work. Comes with matching unstitched blouse piece. Suitable for festivals, weddings, and family celebrations. Available in rich jewel tones.',
            shortDescription: 'Elegant silk blend saree with zari border and blouse piece.',
            price: 5500, originalPrice: 7000, discount: 21, thumbnail: 'https://images.unsplash.com/photo-1583391733981-8498408ee4b6?w=600',
            images: ['https://images.unsplash.com/photo-1583391733981-8498408ee4b6?w=600'],
            category: fashion._id, brand: 'Fabindia', stock: 60, isFeatured: true, gender: 'women',
            tags: ['saree', 'silk saree', 'ethnic wear', 'wedding saree', 'festival wear', 'women traditional'],
            colors: ['red', 'gold'], colorHex: ['#B22222', '#FFD700'], material: ['silk', 'zari'],
            pattern: 'embroidered', aiLabels: ['saree', 'clothing', 'traditional wear', 'ethnic'],
            specifications: [{ key: 'Material', value: 'Silk Blend' }, { key: 'Length', value: '6.3 Meters (with blouse)' }, { key: 'Border', value: 'Zari Gold Work' }, { key: 'Blouse', value: 'Unstitched 0.8m included' }],
            weight: 800, rating: 4.8, reviewCount: 110, totalSold: 280,
        },
        {
            name: 'Men\'s Polo T-Shirt (Navy)', slug: 'mens-polo-t-shirt-navy', sku: 'PLO-006',
            description: 'Classic polo T-shirt in navy blue for men. Made from premium pique cotton for a polished look. Features a two-button placket, ribbed collar and cuffs. Ideal for casual office days, golf, and weekend outings.',
            shortDescription: 'Classic navy pique cotton polo shirt for men.',
            price: 1800, originalPrice: 2200, discount: 18, thumbnail: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600',
            images: ['https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600'],
            category: fashion._id, brand: 'Tommy Hilfiger', stock: 175, gender: 'men',
            tags: ['polo shirt', 'men t-shirt', 'casual shirt', 'navy blue', 'pique cotton'],
            colors: ['navy blue'], colorHex: ['#1F305E'], material: ['cotton', 'pique'],
            pattern: 'solid', aiLabels: ['polo shirt', 't-shirt', 'shirt', 'clothing'],
            specifications: [{ key: 'Material', value: '100% Pique Cotton' }, { key: 'Style', value: 'Classic Polo' }, { key: 'Collar', value: 'Ribbed Polo Collar' }, { key: 'Buttons', value: '2-Button Placket' }],
            weight: 220, rating: 4.5, reviewCount: 38, totalSold: 150,
        },
        {
            name: 'Women\'s Blazer (Tailored Fit)', slug: 'womens-blazer-tailored-fit', sku: 'BLZ-007',
            description: 'Sharp tailored blazer for professional women. Made from premium polyester-viscose blend with a smooth inner lining. Features notched lapels, two front pockets, and a single button closure. Pairs well with trousers or skirts.',
            shortDescription: 'Sharp tailored women\'s blazer for professional settings.',
            price: 4500, originalPrice: 6000, discount: 25, thumbnail: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600',
            images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600'],
            category: fashion._id, brand: 'Massimo Dutti', stock: 55, isFeatured: true, gender: 'women',
            tags: ['blazer', 'women blazer', 'formal wear', 'office blazer', 'jacket', 'professional'],
            colors: ['black', 'charcoal'], colorHex: ['#1A1A1A', '#36454F'], material: ['polyester', 'viscose'],
            pattern: 'solid', aiLabels: ['blazer', 'jacket', 'formal wear', 'coat', 'clothing'],
            specifications: [{ key: 'Material', value: 'Polyester-Viscose Blend' }, { key: 'Lining', value: 'Full Satin Lining' }, { key: 'Closure', value: 'Single Button' }, { key: 'Lapel', value: 'Notched Lapel' }],
            weight: 700, rating: 4.7, reviewCount: 29, totalSold: 95,
        },
        {
            name: 'Printed Graphic Tee (Unisex)', slug: 'printed-graphic-tee-unisex', sku: 'TEE-008',
            description: 'Trendy graphic print T-shirt for men and women. Made from breathable 100% combed cotton. Crew neck, short sleeves, and relaxed fit. Machine washable with colorfast print that stays vibrant after multiple washes.',
            shortDescription: 'Trendy graphic tee, 100% combed cotton, unisex fit.',
            price: 1200, originalPrice: 1500, discount: 20, thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
            images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600'],
            category: fashion._id, brand: 'Bonkers Corner', stock: 300, gender: 'unisex',
            tags: ['graphic tee', 't-shirt', 'unisex', 'printed tee', 'cotton tee', 'casual'],
            colors: ['white', 'black', 'grey'], colorHex: ['#FFFFFF', '#1A1A1A', '#9E9E9E'], material: ['cotton'],
            pattern: 'graphic print', aiLabels: ['t-shirt', 'top', 'clothing', 'casual'],
            specifications: [{ key: 'Material', value: '100% Combed Cotton' }, { key: 'Fit', value: 'Relaxed Fit' }, { key: 'Neck', value: 'Crew Neck' }, { key: 'Print', value: 'Screen Print' }],
            weight: 180, rating: 4.3, reviewCount: 62, totalSold: 410,
        },

        // ── ELECTRONICS (7 products) ──────────────────────────────────
        {
            name: 'Wireless Noise-Cancelling Headphones', slug: 'wireless-noise-cancelling-headphones', sku: 'ELC-009',
            description: 'Premium wireless over-ear headphones with active noise cancellation. Features 30-hour battery life, Bluetooth 5.2, and Hi-Fi audio drivers. The cushioned ear cups and adjustable headband ensure all-day comfort. Folds flat for easy portability.',
            shortDescription: '30-hour battery ANC headphones with Hi-Fi audio.',
            price: 8500, originalPrice: 12000, discount: 29, thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
            images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600', 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600'],
            category: electronics._id, brand: 'Sony', stock: 85, isFeatured: true,
            tags: ['headphones', 'wireless', 'noise cancelling', 'bluetooth', 'audio', 'over ear'],
            colors: ['black', 'silver'], colorHex: ['#1A1A1A', '#C0C0C0'], material: ['plastic', 'memory foam'],
            pattern: 'solid', aiLabels: ['headphone', 'audio device', 'electronics', 'gadget'],
            specifications: [{ key: 'Connectivity', value: 'Bluetooth 5.2' }, { key: 'Battery Life', value: '30 Hours' }, { key: 'Noise Cancellation', value: 'Active (ANC)' }, { key: 'Driver Size', value: '40mm' }, { key: 'Weight', value: '250g' }],
            weight: 250, metaTitle: 'Sony Wireless ANC Headphones', metaDescription: 'Buy premium noise-cancelling wireless headphones.', rating: 4.7, reviewCount: 143, totalSold: 620, isFeatured: true,
        },
        {
            name: 'Smart Watch with Health Monitor', slug: 'smart-watch-health-monitor', sku: 'ELC-010',
            description: 'Feature-packed smartwatch with continuous health monitoring. Tracks heart rate, SpO2, sleep patterns, and 100+ workout modes. 1.4" AMOLED display, IP68 water resistance, and 10-day battery life. Compatible with both Android and iOS.',
            shortDescription: '1.4" AMOLED smartwatch with 10-day battery and health tracking.',
            price: 6500, originalPrice: 9000, discount: 28, thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
            images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600'],
            category: electronics._id, brand: 'Amazfit', stock: 70, isFeatured: true,
            tags: ['smartwatch', 'watch', 'fitness tracker', 'health monitor', 'waterproof', 'amoled'],
            colors: ['black', 'gold', 'silver'], colorHex: ['#1A1A1A', '#FFD700', '#C0C0C0'], material: ['silicone', 'aluminium'],
            aiLabels: ['watch', 'smartwatch', 'wearable', 'gadget', 'electronics'],
            specifications: [{ key: 'Display', value: '1.4" AMOLED' }, { key: 'Battery', value: '10 Days' }, { key: 'Water Resistance', value: 'IP68' }, { key: 'Sensors', value: 'Heart Rate, SpO2, Accelerometer' }, { key: 'Compatibility', value: 'Android & iOS' }],
            weight: 38, rating: 4.5, reviewCount: 87, totalSold: 340,
        },
        {
            name: 'True Wireless Earbuds (TWS)', slug: 'true-wireless-earbuds-tws', sku: 'ELC-011',
            description: 'Crystal-clear true wireless earbuds with active noise cancellation and 28-hour total battery (7h + 21h case). Features touch controls, IPX5 water resistance, and dual mic ENC for clear calls. Perfect for commuting, sports, and work-from-home.',
            shortDescription: 'ANC earbuds with 28-hour total battery, IPX5 rated.',
            price: 3200, originalPrice: 4500, discount: 29, thumbnail: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
            images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600'],
            category: electronics._id, brand: 'OnePlus', stock: 120,
            tags: ['earbuds', 'tws', 'wireless earbuds', 'bluetooth earbuds', 'noise cancelling', 'in ear'],
            colors: ['white', 'black'], colorHex: ['#FFFFFF', '#1A1A1A'], material: ['plastic', 'silicone'],
            aiLabels: ['earbuds', 'headphone', 'audio device', 'electronics'],
            specifications: [{ key: 'Connectivity', value: 'Bluetooth 5.3' }, { key: 'Battery (Buds)', value: '7 Hours' }, { key: 'Battery (Case)', value: '21 Hours' }, { key: 'Water Resistance', value: 'IPX5' }, { key: 'Mic', value: 'Dual ENC Mic' }],
            weight: 45, rating: 4.4, reviewCount: 76, totalSold: 290,
        },
        {
            name: '4K Action Camera Ultra HD', slug: '4k-action-camera-ultra-hd', sku: 'ELC-012',
            description: 'Rugged 4K action camera for adventure enthusiasts. Records at 4K/60fps and 1080p/240fps super slow-motion. Features EIS electronic image stabilization, waterproof up to 30m, and a 2" touch LCD screen. Includes mounting accessories.',
            shortDescription: '4K/60fps action camera, 30m waterproof with EIS stabilization.',
            price: 15000, originalPrice: 20000, discount: 25, thumbnail: 'https://images.unsplash.com/photo-1516035069371-29a1b244ec32?w=600',
            images: ['https://images.unsplash.com/photo-1516035069371-29a1b244ec32?w=600'],
            category: electronics._id, brand: 'GoPro', stock: 40, isFeatured: true,
            tags: ['action camera', '4k camera', 'waterproof camera', 'gopro', 'sports camera', 'vlog'],
            colors: ['black'], colorHex: ['#1A1A1A'], material: ['polycarbonate'],
            aiLabels: ['camera', 'action camera', 'electronics', 'gadget'],
            specifications: [{ key: 'Video', value: '4K @ 60fps' }, { key: 'Slow Motion', value: '1080p @ 240fps' }, { key: 'Waterproof', value: '30 Meters' }, { key: 'Stabilization', value: 'Electronic (EIS)' }, { key: 'Display', value: '2" Touch LCD' }],
            weight: 126, rating: 4.6, reviewCount: 55, totalSold: 180,
        },
        {
            name: 'Portable Bluetooth Speaker (IPX7)', slug: 'portable-bluetooth-speaker-ipx7', sku: 'ELC-013',
            description: '360-degree surround sound portable speaker with deep bass and crystal highs. Features 12-hour battery, IPX7 waterproof rating, and Bluetooth 5.0. The compact cylindrical design is perfect for outdoor trips, beach parties, and camping.',
            shortDescription: '360° sound portable speaker, IPX7 waterproof, 12hr battery.',
            price: 4500, originalPrice: 6000, discount: 25, thumbnail: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600',
            images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600'],
            category: electronics._id, brand: 'JBL', stock: 95,
            tags: ['bluetooth speaker', 'portable speaker', 'waterproof speaker', 'outdoor speaker', 'jbl'],
            colors: ['black', 'red', 'blue'], colorHex: ['#1A1A1A', '#E53935', '#1E90FF'], material: ['plastic', 'rubber'],
            aiLabels: ['speaker', 'bluetooth speaker', 'electronics', 'audio device'],
            specifications: [{ key: 'Connectivity', value: 'Bluetooth 5.0' }, { key: 'Battery', value: '12 Hours' }, { key: 'Water Resistance', value: 'IPX7' }, { key: 'Output', value: '20W' }, { key: 'Sound', value: '360° Surround' }],
            weight: 540, rating: 4.5, reviewCount: 98, totalSold: 450,
        },
        {
            name: 'Mechanical Gaming Keyboard (RGB)', slug: 'mechanical-gaming-keyboard-rgb', sku: 'ELC-014',
            description: 'Full-size mechanical keyboard with per-key RGB backlight. Uses Cherry MX Red switches for fast, linear keystrokes. Features N-key rollover, detachable braided USB-C cable, and aluminum top plate. Ideal for gamers and fast typists.',
            shortDescription: 'Cherry MX Red RGB mechanical keyboard with N-key rollover.',
            price: 7500, originalPrice: 10000, discount: 25, thumbnail: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600',
            images: ['https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600'],
            category: electronics._id, brand: 'Keychron', stock: 60,
            tags: ['gaming keyboard', 'mechanical keyboard', 'rgb keyboard', 'cherry mx', 'gaming peripherals'],
            colors: ['black', 'white'], colorHex: ['#1A1A1A', '#FFFFFF'], material: ['aluminium', 'abs plastic'],
            aiLabels: ['keyboard', 'computer keyboard', 'gaming', 'electronics'],
            specifications: [{ key: 'Switch', value: 'Cherry MX Red' }, { key: 'Backlight', value: 'Per-Key RGB' }, { key: 'Rollover', value: 'N-Key Rollover' }, { key: 'Connection', value: 'USB-C Braided' }, { key: 'Layout', value: 'Full Size 108 Keys' }],
            weight: 1100, rating: 4.6, reviewCount: 64, totalSold: 210,
        },
        {
            name: 'Gaming Mouse (16000 DPI)', slug: 'gaming-mouse-16000-dpi', sku: 'ELC-015',
            description: 'Precision gaming mouse with 16000 DPI adjustable sensor and 7 programmable buttons. Features RGB lighting with 16.8M colors, 1000Hz polling rate, and a comfortable ergonomic design. Compatible with major gaming software.',
            shortDescription: '16000 DPI gaming mouse with 7 programmable buttons.',
            price: 3500, originalPrice: 5000, discount: 30, thumbnail: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600',
            images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600'],
            category: electronics._id, brand: 'Razer', stock: 80,
            tags: ['gaming mouse', 'mouse', 'rgb mouse', 'high dpi', 'razer', 'gaming peripheral'],
            colors: ['black'], colorHex: ['#1A1A1A'], material: ['plastic', 'rubber'],
            aiLabels: ['computer mouse', 'mouse', 'gaming', 'electronics', 'peripheral'],
            specifications: [{ key: 'DPI', value: '200 - 16000 DPI' }, { key: 'Buttons', value: '7 Programmable' }, { key: 'Polling Rate', value: '1000Hz' }, { key: 'Lighting', value: 'Chroma RGB (16.8M)' }, { key: 'Weight', value: '95g' }],
            weight: 95, rating: 4.5, reviewCount: 72, totalSold: 300,
        },

        // ── SHOES (6 products) ────────────────────────────────────────
        {
            name: 'Men\'s Running Sneakers (Lightweight)', slug: 'mens-running-sneakers-lightweight', sku: 'SHO-016',
            description: 'High-performance ultralight running sneakers with responsive cushioning. Features a breathable mesh upper, EVA foam midsole for shock absorption, and rubber outsole for superior grip. Suitable for daily runs, gym, and casual wear.',
            shortDescription: 'Ultralight mesh running sneakers with EVA foam cushioning.',
            price: 5500, originalPrice: 7500, discount: 27, thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
            images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600'],
            category: shoes._id, brand: 'Nike', stock: 130, isFeatured: true, gender: 'men',
            tags: ['running shoes', 'sneakers', 'men shoes', 'sports shoes', 'lightweight', 'mesh shoes'],
            colors: ['white', 'orange', 'blue'], colorHex: ['#FFFFFF', '#FF6B35', '#1E90FF'], material: ['mesh', 'rubber', 'eva foam'],
            pattern: 'solid', aiLabels: ['sneaker', 'shoe', 'running shoe', 'athletic shoe', 'footwear'],
            specifications: [{ key: 'Upper', value: 'Breathable Mesh' }, { key: 'Midsole', value: 'EVA Foam' }, { key: 'Outsole', value: 'Rubber' }, { key: 'Closure', value: 'Lace-Up' }, { key: 'Weight', value: '280g (per shoe)' }],
            weight: 560, rating: 4.8, reviewCount: 165, totalSold: 580,
        },
        {
            name: 'Women\'s White Canvas Sneakers', slug: 'womens-white-canvas-sneakers', sku: 'SHO-017',
            description: 'Classic white canvas sneakers for women. Clean, minimal design with a vulcanized rubber sole. Features a cushioned insole for all-day comfort. Goes with everything from jeans to dresses. Easy to clean and perfect for everyday wear.',
            shortDescription: 'Classic minimal white canvas sneakers for everyday wear.',
            price: 2800, originalPrice: 3500, discount: 20, thumbnail: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600',
            images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600'],
            category: shoes._id, brand: 'Converse', stock: 110, gender: 'women',
            tags: ['canvas shoes', 'white sneakers', 'women shoes', 'casual shoes', 'flat shoes', 'minimal shoes'],
            colors: ['white'], colorHex: ['#FFFFFF'], material: ['canvas', 'rubber'],
            aiLabels: ['sneaker', 'shoe', 'canvas shoe', 'footwear', 'flat shoe'],
            specifications: [{ key: 'Upper', value: 'Canvas' }, { key: 'Sole', value: 'Vulcanized Rubber' }, { key: 'Insole', value: 'Cushioned' }, { key: 'Closure', value: 'Lace-Up' }],
            weight: 420, rating: 4.5, reviewCount: 89, totalSold: 360,
        },
        {
            name: 'Leather Oxford Formal Shoes (Men)', slug: 'leather-oxford-formal-shoes-men', sku: 'SHO-018',
            description: 'Genuine leather Oxford formal shoes crafted for professional settings. Features a Goodyear welt construction for durability, cushioned leather insole, and a leather outsole. A pair that gets better with age and use.',
            shortDescription: 'Genuine leather Oxford shoes with Goodyear welt construction.',
            price: 8500, originalPrice: 11000, discount: 23, thumbnail: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600',
            images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600'],
            category: shoes._id, brand: 'Clarks', stock: 45, gender: 'men',
            tags: ['oxford shoes', 'formal shoes', 'leather shoes', 'men formal', 'dress shoes', 'office shoes'],
            colors: ['brown', 'black'], colorHex: ['#6B3A2A', '#1A1A1A'], material: ['genuine leather'],
            aiLabels: ['shoe', 'dress shoe', 'oxford', 'formal shoe', 'footwear'],
            specifications: [{ key: 'Upper', value: 'Genuine Leather' }, { key: 'Sole', value: 'Leather + Rubber' }, { key: 'Construction', value: 'Goodyear Welt' }, { key: 'Lining', value: 'Leather Lined' }, { key: 'Style', value: 'Oxford' }],
            weight: 900, rating: 4.6, reviewCount: 42, totalSold: 120,
        },
        {
            name: 'Ankle Boots (Women, Block Heel)', slug: 'ankle-boots-women-block-heel', sku: 'SHO-019',
            description: 'Trendy block heel ankle boots in faux suede material. Features a side zip closure for easy wear, cushioned footbed, and a stable 6cm block heel. Perfect for autumn-winter fashion and transitional outfits.',
            shortDescription: 'Faux suede block-heel ankle boots with side zip.',
            price: 4500, originalPrice: 6000, discount: 25, thumbnail: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
            images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600'],
            category: shoes._id, brand: 'Steve Madden', stock: 65, gender: 'women',
            tags: ['ankle boots', 'women boots', 'block heel', 'suede boots', 'winter shoes', 'heeled boots'],
            colors: ['camel', 'black', 'grey'], colorHex: ['#C19A6B', '#1A1A1A', '#808080'], material: ['faux suede', 'synthetic'],
            aiLabels: ['boot', 'ankle boot', 'shoe', 'footwear', 'women shoe'],
            specifications: [{ key: 'Material', value: 'Faux Suede' }, { key: 'Heel Height', value: '6 cm Block Heel' }, { key: 'Closure', value: 'Side Zip' }, { key: 'Toe', value: 'Almond Toe' }],
            weight: 700, rating: 4.4, reviewCount: 58, totalSold: 195,
        },
        {
            name: 'Sports Sandals (Unisex, Trail)', slug: 'sports-sandals-unisex-trail', sku: 'SHO-020',
            description: 'Rugged trail sports sandals with adjustable straps and a grippy Vibram outsole. Water-friendly, quick-dry upper and a contoured footbed for arch support. Ideal for hiking, water sports, and outdoor adventures.',
            shortDescription: 'Vibram-soled trail sandals with adjustable straps and arch support.',
            price: 3200, originalPrice: 4000, discount: 20, thumbnail: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600',
            images: ['https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600'],
            category: shoes._id, brand: 'Teva', stock: 90, gender: 'unisex',
            tags: ['sandals', 'sports sandals', 'trail', 'outdoor', 'water-friendly', 'unisex shoes'],
            colors: ['brown', 'olive', 'navy'], colorHex: ['#6B3A2A', '#6B7645', '#1F305E'], material: ['nylon webbing', 'rubber'],
            aiLabels: ['sandal', 'sports sandal', 'shoe', 'footwear', 'outdoor shoe'],
            specifications: [{ key: 'Outsole', value: 'Vibram Rubber' }, { key: 'Upper', value: 'Quick-Dry Nylon Webbing' }, { key: 'Straps', value: '3-Point Adjustable' }, { key: 'Footbed', value: 'Contoured Arch Support' }],
            weight: 380, rating: 4.3, reviewCount: 34, totalSold: 140,
        },
        {
            name: 'High-Top Basketball Shoes', slug: 'high-top-basketball-shoes', sku: 'SHO-021',
            description: 'Professional high-top basketball shoes with ankle support and Air cushioning. Features a herringbone outsole for multi-directional grip, breathable mesh panels, and extra ankle padding. Built for court performance at all levels.',
            shortDescription: 'High-top basketball shoes with Air cushion and herringbone grip.',
            price: 9000, originalPrice: 12000, discount: 25, thumbnail: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600',
            images: ['https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600'],
            category: shoes._id, brand: 'Air Jordan', stock: 55, isFeatured: true, gender: 'unisex',
            tags: ['basketball shoes', 'high top', 'sports shoes', 'air cushion', 'jordan', 'court shoes'],
            colors: ['red', 'black', 'white'], colorHex: ['#CC0000', '#1A1A1A', '#FFFFFF'], material: ['mesh', 'rubber', 'foam'],
            aiLabels: ['sneaker', 'basketball shoe', 'shoe', 'athletic shoe', 'footwear'],
            specifications: [{ key: 'Style', value: 'High-Top' }, { key: 'Cushioning', value: 'Air Unit' }, { key: 'Outsole', value: 'Herringbone Rubber' }, { key: 'Upper', value: 'Mesh + Leather' }, { key: 'Ankle', value: 'Padded Ankle Support' }],
            weight: 680, rating: 4.7, reviewCount: 78, totalSold: 250,
        },

        // ── ACCESSORIES (5 products) ──────────────────────────────────
        {
            name: 'Premium Leather Wallet (Slim)', slug: 'premium-leather-wallet-slim', sku: 'ACC-022',
            description: 'Ultra-slim bifold wallet made from full-grain vegetable-tanned leather. Holds 6-8 cards and cash. Features RFID blocking protection, stitched edges, and develops a beautiful patina over time. A perfect everyday carry.',
            shortDescription: 'Full-grain leather slim RFID bifold wallet.',
            price: 2200, originalPrice: 2800, discount: 21, thumbnail: 'https://images.unsplash.com/photo-1627123424574-724758594785?w=600',
            images: ['https://images.unsplash.com/photo-1627123424574-724758594785?w=600'],
            category: accessories._id, brand: 'Bellroy', stock: 100, gender: 'men',
            tags: ['wallet', 'leather wallet', 'slim wallet', 'rfid wallet', 'bifold', 'men accessories'],
            colors: ['brown', 'black', 'tan'], colorHex: ['#6B3A2A', '#1A1A1A', '#C19A6B'], material: ['full-grain leather'],
            aiLabels: ['wallet', 'leather wallet', 'accessory'],
            specifications: [{ key: 'Material', value: 'Full-Grain Veg-Tan Leather' }, { key: 'Protection', value: 'RFID Blocking' }, { key: 'Card Slots', value: '6-8 Cards' }, { key: 'Style', value: 'Slim Bifold' }],
            weight: 60, rating: 4.7, reviewCount: 95, totalSold: 380,
        },
        {
            name: 'Polarized Aviator Sunglasses', slug: 'polarized-aviator-sunglasses', sku: 'ACC-023',
            description: 'Classic aviator sunglasses with polarized glass lenses that reduce glare and UV100% protection. Lightweight metal frame with adjustable nose pads and spring hinges for a comfortable fit. Suitable for driving, outdoor activities, and everyday use.',
            shortDescription: 'UV400 polarized aviator shades with lightweight metal frame.',
            price: 3500, originalPrice: 5000, discount: 30, thumbnail: 'https://images.unsplash.com/photo-1509695507497-903c140c43b0?w=600',
            images: ['https://images.unsplash.com/photo-1509695507497-903c140c43b0?w=600'],
            category: accessories._id, brand: 'Ray-Ban', stock: 75, gender: 'unisex',
            tags: ['sunglasses', 'aviator', 'polarized', 'ray-ban', 'eyewear', 'uv protection'],
            colors: ['gold', 'silver', 'black'], colorHex: ['#FFD700', '#C0C0C0', '#1A1A1A'], material: ['metal', 'glass'],
            aiLabels: ['sunglasses', 'eyewear', 'glasses', 'accessory'],
            specifications: [{ key: 'Lens', value: 'Polarized Glass' }, { key: 'UV Protection', value: 'UV400' }, { key: 'Frame', value: 'Lightweight Metal' }, { key: 'Nose Pads', value: 'Adjustable Silicone' }, { key: 'Hinge', value: 'Spring Hinge' }],
            weight: 28, rating: 4.6, reviewCount: 112, totalSold: 490,
        },
        {
            name: 'Canvas Backpack (Laptop, 30L)', slug: 'canvas-backpack-laptop-30l', sku: 'ACC-024',
            description: 'Versatile 30L canvas backpack with a dedicated padded 15.6" laptop compartment. Features multiple organization pockets, a USB charging port, and ergonomic padded shoulder straps. Water-resistant canvas exterior suitable for daily commute and travel.',
            shortDescription: '30L canvas backpack with USB port and padded laptop sleeve.',
            price: 4200, originalPrice: 5500, discount: 24, thumbnail: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
            images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'],
            category: accessories._id, brand: 'Herschel', stock: 88, gender: 'unisex',
            tags: ['backpack', 'laptop bag', 'canvas bag', 'school bag', 'travel bag', 'men bag'],
            colors: ['olive', 'navy', 'black', 'grey'], colorHex: ['#6B7645', '#1F305E', '#1A1A1A', '#808080'], material: ['canvas', 'polyester'],
            aiLabels: ['backpack', 'bag', 'laptop bag', 'accessory'],
            specifications: [{ key: 'Capacity', value: '30 Litres' }, { key: 'Laptop Compartment', value: '15.6"' }, { key: 'Material', value: 'Water-Resistant Canvas' }, { key: 'USB Port', value: 'External USB Charging Port' }, { key: 'Straps', value: 'Padded Ergonomic' }],
            weight: 900, rating: 4.5, reviewCount: 67, totalSold: 230,
        },
        {
            name: 'Stainless Steel Chain Bracelet (Men)', slug: 'stainless-steel-chain-bracelet-men', sku: 'ACC-025',
            description: 'Heavy-duty stainless steel chain bracelet with a sleek gunmetal finish. Hypoallergenic, tarnish-resistant, and waterproof. Features a lobster claw clasp for secure wear. A bold statement piece for everyday styling.',
            shortDescription: 'Hypoallergenic stainless steel chain bracelet in gunmetal finish.',
            price: 1500, originalPrice: 2000, discount: 25, thumbnail: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600',
            images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600'],
            category: accessories._id, brand: 'Fossil', stock: 150, gender: 'men',
            tags: ['bracelet', 'chain bracelet', 'men jewellery', 'steel bracelet', 'gunmetal', 'accessories'],
            colors: ['silver', 'gunmetal', 'gold'], colorHex: ['#C0C0C0', '#2E2E2E', '#FFD700'], material: ['stainless steel'],
            aiLabels: ['bracelet', 'jewellery', 'chain', 'accessory'],
            specifications: [{ key: 'Material', value: '316L Stainless Steel' }, { key: 'Finish', value: 'Gunmetal PVD' }, { key: 'Clasp', value: 'Lobster Claw' }, { key: 'Width', value: '8mm' }],
            weight: 55, rating: 4.4, reviewCount: 43, totalSold: 220,
        },
        {
            name: 'Minimalist Leather Belt (Men)', slug: 'minimalist-leather-belt-men', sku: 'ACC-026',
            description: 'Clean minimalist full-grain leather belt with a brushed metal pin buckle. Suits both formal and smart-casual outfits. Available in multiple sizes, this belt adds a refined finish to any outfit.',
            shortDescription: 'Full-grain leather belt with brushed metal pin buckle.',
            price: 1800, originalPrice: 2400, discount: 25, thumbnail: 'https://images.unsplash.com/photo-1553531889-e6cf4d692b1b?w=600',
            images: ['https://images.unsplash.com/photo-1553531889-e6cf4d692b1b?w=600'],
            category: accessories._id, brand: 'Allen Edmonds', stock: 120, gender: 'men',
            tags: ['belt', 'leather belt', 'men belt', 'formal belt', 'minimalist', 'pin buckle'],
            colors: ['brown', 'black'], colorHex: ['#6B3A2A', '#1A1A1A'], material: ['full-grain leather', 'metal'],
            aiLabels: ['belt', 'leather belt', 'accessory', 'clothing accessory'],
            specifications: [{ key: 'Material', value: 'Full-Grain Leather' }, { key: 'Buckle', value: 'Brushed Metal Pin' }, { key: 'Width', value: '35mm' }, { key: 'Sizes', value: '28" to 44"' }],
            weight: 180, rating: 4.5, reviewCount: 39, totalSold: 175,
        },

        // ── HOME & LIVING (2 products) ────────────────────────────────
        {
            name: 'Luxury Scented Soy Candle Set (3pcs)', slug: 'luxury-scented-soy-candle-set', sku: 'HOM-027',
            description: 'Hand-poured soy wax scented candles in a curated gift set of three. Fragrances: Sandalwood & Amber, Lavender & Vanilla, and Eucalyptus & Mint. Each burns 40+ hours with a cotton wick for a clean flame. Packaged in an elegant gift box.',
            shortDescription: 'Set of 3 hand-poured soy candles - 40+ hour burn time each.',
            price: 2800, originalPrice: 3500, discount: 20, thumbnail: 'https://images.unsplash.com/photo-1602607046734-8c4e2c16cfa0?w=600',
            images: ['https://images.unsplash.com/photo-1602607046734-8c4e2c16cfa0?w=600'],
            category: home._id, brand: 'Yankee Candle', stock: 60, isFeatured: true,
            tags: ['candle', 'scented candle', 'soy candle', 'gift set', 'home decor', 'aroma'],
            colors: ['cream', 'beige', 'white'], colorHex: ['#F5F5DC', '#D2C5A0', '#FFFFFF'], material: ['soy wax', 'glass'],
            aiLabels: ['candle', 'home decor', 'aromatherapy', 'gift'],
            specifications: [{ key: 'Wax', value: '100% Natural Soy' }, { key: 'Wick', value: 'Cotton (lead-free)' }, { key: 'Burn Time', value: '40+ Hours each' }, { key: 'Quantity', value: '3 Candles' }, { key: 'Fragrance', value: 'Sandalwood, Lavender, Eucalyptus' }],
            weight: 750, rating: 4.8, reviewCount: 84, totalSold: 310,
        },
        {
            name: 'Premium Weighted Blanket (7kg)', slug: 'premium-weighted-blanket-7kg', sku: 'HOM-028',
            description: 'Therapeutic 7kg weighted blanket that promotes deep, restful sleep. Made from breathable microfiber with even glass bead fill distribution. Features a removable, washable cover in a soft mink fabric. Perfect for adults with anxiety or sleep issues.',
            shortDescription: '7kg microfiber weighted blanket with removable mink cover.',
            price: 5500, originalPrice: 7000, discount: 21, thumbnail: 'https://images.unsplash.com/photo-1631048036429-fcb3e9e6e93d?w=600',
            images: ['https://images.unsplash.com/photo-1631048036429-fcb3e9e6e93d?w=600'],
            category: home._id, brand: 'Luna', stock: 45,
            tags: ['weighted blanket', 'sleep blanket', 'therapeutic', 'anxiety blanket', 'bedding'],
            colors: ['grey', 'navy', 'white'], colorHex: ['#808080', '#1F305E', '#FFFFFF'], material: ['microfiber', 'glass beads', 'mink'],
            aiLabels: ['blanket', 'bedding', 'home', 'sleeping'],
            specifications: [{ key: 'Weight', value: '7 Kg' }, { key: 'Fill', value: 'Glass Beads' }, { key: 'Outer', value: 'Microfiber' }, { key: 'Cover', value: 'Removable Mink Cover' }, { key: 'Size', value: '150x200 cm' }],
            weight: 7000, rating: 4.6, reviewCount: 56, totalSold: 190,
        },

        // ── SPORTS (2 products) ───────────────────────────────────────
        {
            name: 'Pro Yoga Mat (Non-Slip, 6mm)', slug: 'pro-yoga-mat-non-slip-6mm', sku: 'SPT-029',
            description: 'Professional 6mm thick TPE yoga mat with double-sided non-slip texture. Eco-friendly, odor-resistant material that provides excellent grip on all floor types. Includes a carrying strap for easy transport. Suitable for yoga, pilates, and stretching.',
            shortDescription: '6mm TPE eco-friendly non-slip yoga mat with carry strap.',
            price: 2500, originalPrice: 3200, discount: 22, thumbnail: 'https://images.unsplash.com/photo-1601925228560-7b49408a4a4a?w=600',
            images: ['https://images.unsplash.com/photo-1601925228560-7b49408a4a4a?w=600'],
            category: sports._id, brand: 'Manduka', stock: 100, gender: 'unisex',
            tags: ['yoga mat', 'exercise mat', 'non-slip mat', 'pilates', 'gym mat', 'eco friendly'],
            colors: ['purple', 'teal', 'black', 'pink'], colorHex: ['#8B5CF6', '#14B8A6', '#1A1A1A', '#EC4899'], material: ['tpe'],
            aiLabels: ['yoga mat', 'exercise mat', 'sports equipment', 'mat'],
            specifications: [{ key: 'Material', value: 'TPE (Eco-Friendly)' }, { key: 'Thickness', value: '6mm' }, { key: 'Size', value: '183 x 61 cm' }, { key: 'Surface', value: 'Double-Sided Non-Slip' }, { key: 'Includes', value: 'Carry Strap' }],
            weight: 1200, rating: 4.7, reviewCount: 73, totalSold: 320,
        },
        {
            name: 'Adjustable Dumbbell Set (5-25kg)', slug: 'adjustable-dumbbell-set-5-25kg', sku: 'SPT-030',
            description: 'Space-saving adjustable dumbbell set that replaces 9 pairs of weights. Dial selector adjusts from 5kg to 25kg in 2.5kg increments. Made from durable steel with a non-slip grip handle. Ideal for home gym workouts targeting all muscle groups.',
            shortDescription: 'Adjustable 5-25kg dumbbell set, replaces 9 pairs of weights.',
            price: 18000, originalPrice: 25000, discount: 28, thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600',
            images: ['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600'],
            category: sports._id, brand: 'Bowflex', stock: 30, isFeatured: true,
            tags: ['dumbbell', 'adjustable dumbbell', 'home gym', 'weights', 'fitness equipment', 'strength training'],
            colors: ['black', 'grey'], colorHex: ['#1A1A1A', '#808080'], material: ['steel', 'rubber'],
            aiLabels: ['dumbbell', 'weight', 'gym equipment', 'fitness', 'sports'],
            specifications: [{ key: 'Weight Range', value: '5kg - 25kg' }, { key: 'Increment', value: '2.5kg Steps' }, { key: 'Replaces', value: '9 Pairs of Dumbbells' }, { key: 'Handle', value: 'Non-Slip Ergonomic' }, { key: 'Adjustment', value: 'Dial Selector' }],
            weight: 50000, rating: 4.8, reviewCount: 45, totalSold: 120,
        },
    ];

    await Product.insertMany(products);
    console.log(`✅ ${products.length} products inserted!`);

    console.log('\n🎉 Database seeded successfully!');
    process.exit(0);
}

seed().catch(err => {
    console.error('❌ Seed failed:', err);
    process.exit(1);
});
